#!/bin/bash
EX='^[0-9]+$'
PROJ='^P[0-9]+$'
EXAM='^E[1-3]P[0-9]+$'
source PATHS
INSTBIN=''
if [[ $1 =~ $EX ]]; then
   ASGN="Exercise$1"
   ASGNDIR=$EXERCISEDIR
   REMOTEASGNDIR=$REMOTEEXERCISEDIR
   INSTDIR="/home/kmammen/357/$ASGN"
   HANDINDIR=$ASGN-Section7
elif [[ $1 =~ $PROJ ]]; then
   ASGN="Project${1:1:${#1}-1}"
   ASGNDIR=$PROJECTDIR
   REMOTEASGNDIR=$REMOTEPROJECTDIR
   INSTDIR="/home/kmammen/357/$ASGN"
   HANDINDIR=$ASGN
elif [[ $1 =~ $EXAM ]]; then
   ASGN="Exam${1:1:${#1}-1}"
   ASGNDIR=$EXAMDIR
   REMOTEASGNDIR=$REMOTEEXAMDIR
   HANDINDIR=$ASGN-Section7
   INSTBIN="/home/kmammen/357/Exam${1:1:1}/$EXAMCODE/${1:2:${#1}-1}/reference"
elif [[ $1 =~ '^Exercise[0-9]+$' ]]; then
   ASGN=$1
   ASGNDIR=$EXERCISEDIR
   REMOTEASGNDIR=$REMOTEEXERCISEDIR
   INSTDIR="/home/kmammen/357/$ASGN"
   HANDINDIR=$ASGN-Section7
elif [[ $1 =~ '^Exam[1-3]P[0-9]+$' ]]; then
   ASGN=$1
   ASGNDIR=$EXAMDIR
   REMOTEASGNDIR=$REMOTEEXAMDIR
   HANDINDIR=$ASGN-Section7
   INSTBIN="/home/kmammen/357/${1:0:4}/$EXAMCODE/${1:5:${#1}-1}/reference"
else
   ASGN=$1
   ASGNDIR=$PROJDIR
   INSTDIR="/home/kmammen/357/$ASGN"
   REMOTEASGNDIR=$REMOTEPROJECTDIR
   HANDINDIR=$ASGN
fi

