#!/bin/bash
if [[ $# == 0 ]]; then
   echo "Usage: "
   echo "   $0 <ASGN_NAME> [arguments]"
   echo
   echo "<ASGN_NAME> can be in any of the following formats:"
   echo "      #           Ex. $0 1 (calls Exercise1)"
   echo "      P#          Ex. $0 P1 (calls Project1)"
   echo "      Exercise#   Ex. $0 Exercise1"
   echo "      Project#    Ex. $0 Project1"
   echo
   echo "Any additional arguments specified will be passed to the executable verbatim"
   exit 1
fi
if [ -n "$SSH_CLIENT" ] ; then 
   set -e
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$REMOTEASGNDIR"
   . $CURDIR/getinst $ASGN
   cd "$REMOTEASGNDIR/$ASGN"
   echo "Instructor Output:"
   echo
   $INSTBIN ${@:2}
   echo
else
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$ASGNDIR"
   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "$REMOTEDIR/inst ${@:1}"
fi

