#!/bin/bash
set -e
ASGN=$1
DIR="/home/kmammen/357/$ASGN"
if [ ! -d $DIR ]; then
   echo "$ASGN not found!"
   exit
fi
cd $DIR
NUM=0
FILES=( )
for f in *; do
   if [ -f "$f" ] && [ -x "$f" ]; then
      FILES[$NUM]=$f
      NUM=$((NUM+1))
   fi
done
INST=0
if [[ $NUM == 0 ]]; then
   echo "No executable found!"
   exit
fi
if [[ $NUM > 1 ]]; then
   echo "Multiple executables found!"
   for (( i = 0; i < $NUM; i++ )); do
      echo "$i: ${FILES[$i]}"
   done
   echo "Which one? "
   read INST
fi

./${FILES[$INST]} ${@:2}

