#!/bin/bash
if [[ $# == 0 ]]; then
   echo "Usage: "
   echo "   $0 <ASGN_NAME>"
   echo
   echo "<ASGN_NAME> can be in any of the following formats:"
   echo "      #           Ex. $0 1 (calls Exercise1)"
   echo "      P#          Ex. $0 P1 (calls Project1)"
   echo "      Exercise#   Ex. $0 Exercise1"
   echo "      Project#    Ex. $0 Project1"
   exit 1
fi
if [ -n "$SSH_CLIENT" ] ; then 
   set -e
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$REMOTEASGNDIR"
   cd $ASGN
   make clean
   make
   NUM=1
   FILE="in$NUM"
   while [ -e "$FILE" ]; do
      NUM=$((NUM+1))
      FILE="in$NUM"
   done

   echo "Command line args?"
   read ARGS
   
   echo "Writing to $FILE! Type quit to finish"
   echo $ARGS > $FILE

   while read line && [ "$line" != "quit" ]; do
      echo $line >> $FILE
   done
   set +e
   cd $ASGNDIR/$ASGN
   tail -n +2 $FILE | ./a.out `head -1 $FILE` > $FILE.myout 2> $FILE.myerr
   MYEXIT=$?
   . $CURDIR/getinst $ASGN
   cd $ASGNDIR/$ASGN
   tail -n +2 $FILE | $INSTBIN `head -1 $FILE` > $FILE.out 2> $FILE.err
   INSTEXIT=$?
   echo
   diff $FILE.out $FILE.myout
   diff $FILE.err $FILE.myerr
   if [[ $MYEXIT != $INSTEXIT ]]; then
      echo "Expected $INSTEXIT return val, found $MYEXIT"
   fi
else
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$ASGNDIR"
   rsync -av $ASGN/* "$CPUSER@unix$UNIX.csc.calpoly.edu:$REMOTEASGNDIR/$ASGN" > /dev/null
   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "$REMOTEDIR/newtest ${@:1}"
   rsync -av $CPUSER@unix$UNIX.csc.calpoly.edu:$REMOTEASGNDIR/$ASGN/in* $ASGN > /dev/null
fi

