#!/bin/bash

# Set these variables if you want to edit on your local environment
LOCALDIR="$HOME/Documents/Cal Poly/CPE 357"
PROJECTDIR="$LOCALDIR"
EXERCISEDIR="$LOCALDIR"

# CSL Server variables (MUST BE SET)
CPUSER="smalik01"
UNIX=12

# You MUST set these variables for ANY of my scripts to work!!
REMOTEDIR="/home/$CPUSER/cpe357"
REMOTEPROJECTDIR=$REMOTEDIR
REMOTEEXERCISEDIR=$REMOTEDIR

# Exam vars! Put the code in EXAMCODE
REMOTEEXAMDIR=$REMOTEDIR
EXAMDIR="$LOCALDIR"
EXAMCODE=123456
