#!/bin/bash
if [[ $# == 0 ]]; then
   echo "Usage: "
   echo "   $0 <ASGN_NAME>"
   echo
   echo "<ASGN_NAME> can be in any of the following formats:"
   echo "      #           Ex. $0 1 (calls Exercise1)"
   echo "      P#          Ex. $0 P1 (calls Project1)"
   echo "      Exercise#   Ex. $0 Exercise1"
   echo "      Project#    Ex. $0 Project1"
   exit 1
fi
if [ -n "$SSH_CLIENT" ] ; then 
   set -e
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$REMOTEASGNDIR"
   if [ ! -d $ASGN ]; then
      echo "Invalid assignment: $ASGN"
      exit 2
   fi
   cd $ASGN
   make clean
   make
   echo "Program Output:"
   echo
   ./a.out ${@:2}
   echo
else
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$ASGNDIR"
   rsync -av $ASGN/* "$CPUSER@unix$UNIX.csc.calpoly.edu:$REMOTEASGNDIR/$ASGN" > /dev/null
   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "$REMOTEDIR/run ${@:1}"
fi

