#!/bin/bash
if [[ $# == 0 ]]; then
   echo "Usage: "
   echo "   $0 <ASGN_NAME>"
   echo
   echo "<ASGN_NAME> can be in any of the following formats:"
   echo "      #           Ex. $0 1 (calls Exercise1)"
   echo "      P#          Ex. $0 P1 (calls Project1)"
   echo "      Exercise#   Ex. $0 Exercise1"
   echo "      Project#    Ex. $0 Project1"
   exit 1
fi
if [ -n "$SSH_CLIENT" ] ; then 
   set -e
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$REMOTEASGNDIR"
   cd $ASGN
   make clean
   make
   #Inst
   DIR="/home/kmammen/357/$ASGN"
   if [ ! -d $DIR ]; then
      echo "$ASGN not found!"
      exit
   fi
   cd $DIR
   NUM=0
   FILES=( )
   for f in *; do
      if [ -f "$f" ] && [ -x "$f" ]; then
         FILES[$NUM]=$f
         NUM=$((NUM+1))
      fi
   done
   INST=0
   if [[ $NUM == 0 ]]; then
      echo "No executable found!"
      exit
   fi
   if [[ $NUM > 1 ]]; then
      echo "Multiple executables found!"
      for (( i = 0; i < $NUM; i++ )); do
         echo "$i: ${FILES[$i]}"
      done
      echo "Which one? "
      read INST
   fi
   NUM=1
   cd $HOME/cpe357/$ASGN

   FILE="in$NUM"
   set +e
   while [ -e "$FILE" ]; do
      echo "Running $FILE"
      tail -n +2 $FILE | ./a.out `head -1 $FILE` > $FILE.myout 2> $FILE.myerr
      tail -n +2 $FILE | $DIR/${FILES[$INST]} `head -1 $FILE` > $FILE.out 2> $FILE.err
      diff $FILE.out $FILE.myout
      diff $FILE.err $FILE.myerr
      NUM=$((NUM+1))
      FILE="in$NUM"
   done

   echo

else
   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   cd "$CURDIR"
   . ./getasgn $1
   cd "$ASGNDIR"
   rsync -av $ASGN/* "$CPUSER@unix$UNIX.csc.calpoly.edu:/$REMOTEASGNDIR/$ASGN" > /dev/null
   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "/$REMOTEDIR/runtests ${@:1}"
   rsync -av $CPUSER@unix$UNIX.csc.calpoly.edu:/$REMOTEASGNDIR/$ASGN/in* $ASGN > /dev/null
fi

